#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from typing import Any, Mapping, Optional, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


def agent_rubrik_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[object]:
    args = ["--user", params["user"], "--secret", passwordstore_get_cmdline("%s", params["secret"])]
    if params.get("verify_ssl"):
        args += ["--verify_ssl"]
    args += ["--hostname", hostname]
    if params.get("sections"):
        args += ["--sections", ",".join(params["sections"])]

    return args


special_agent_info["rubrik"] = agent_rubrik_arguments
