#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def agent_rubrik_arguments(params, hostname, ipaddress):
    args = ["--user", params["user"]]
    args += ["--hostname", hostname]
    args += ["--secret", passwordstore_get_cmdline("%s", params["secret"])]
    if params.get("verify_ssl"):
        args += ["--verify_ssl", params["verify_ssl"]]

    return args


special_agent_info["rubrik"] = agent_rubrik_arguments
