#!/usr/bin/env python3

from __future__ import annotations

import argparse
import sys
from typing import Any

import cmk.utils.password_store
import requests
import urllib3
from urllib3.exceptions import InsecureRequestWarning

cmk.utils.password_store.replace_passwords()
urllib3.disable_warnings(InsecureRequestWarning)


sections = [
    "cluster_system_status",
    "cluster_compliance_status",
    "node_status",
    "node_disk_status",
    "node_hardware_health",
]


class RubrikRestApi:
    def __init__(
        self,
        hostname: str,
        username: str,
        password: str,
        *,
        verify: bool = False,
    ) -> None:
        """Provide a simple helper around the Rubrik REST API."""
        self.base_rubrik_url = f"https://{hostname}/api/"
        self.session: requests.Session | None = None
        self.verify = verify
        if not self.verify:
            urllib3.disable_warnings(InsecureRequestWarning)
        self.username = username
        self.password = password
        self.token: str | None = None

    def login(self) -> None:
        self.session = requests.Session()
        self.session.headers["accept"] = "application/json"
        try:
            response = self.session.post(
                url=f"{self.base_rubrik_url}v1/service_account/session",
                json={"serviceAccountId": self.username, "secret": self.password},
                verify=self.verify,
            )
            response.raise_for_status()
        except requests.RequestException as exc:
            sys.stderr.write(f"Request error: {exc}")
            sys.exit(1)

        response_json = response.json()
        if response_json.get("errorType") == "user_error":
            sys.stderr.write(f"Login error: {response_json.get('message')}")
            sys.exit(1)

        self.token = response_json.get("token")
        self.session.headers.update(
            {
                "Authorization": f"Bearer {self.token}",
            },
        )

    def delete_token(self) -> int:
        if not self.token or not self.session:
            return 0

        try:
            self.session.delete(url=f"{self.base_rubrik_url}v1/session/me", verify=self.verify)
        except requests.RequestException as exc:
            sys.stderr.write(f"Token delete error: {exc}")
            return 1
        return 0

    def get_endpoint_data(self, endpoint: str) -> dict[str, Any]:
        if not self.session:
            return {}
        try:
            response = self.session.get(url=f"{self.base_rubrik_url}{endpoint}", verify=self.verify)
            response.raise_for_status()
        except requests.RequestException as exc:
            print(f"Request error: {exc}")
            return {}

        try:
            return response.json()
        except ValueError:
            return {}


def parse_arguments(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--user", help="User Name for API Calls", required=True)
    parser.add_argument("--secret", help="Secret of User", required=True)
    parser.add_argument("--hostname", help="Hostname to make calls to", required=True)
    parser.add_argument(
        "--verify_ssl",
        help="Disable SSL certificate verification",
        action="store_true",
    )
    parser.add_argument(
        "--sections",
        type=lambda s: s.split(","),
        default=sections,
        help=f"Sections to query. This is a comma separated list of {', '.join(sections)}. Default is to query all sections.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_arguments(argv)
    api = RubrikRestApi(
        username=args.user,
        password=args.secret,
        verify=args.verify_ssl,
        hostname=args.hostname,
    )

    api.login()

    # Cluster Data
    # System Status
    if "cluster_system_status" in args.sections:
        print("<<<rubrik_cluster_system_status:sep(0)>>>")
        print(api.get_endpoint_data("internal/cluster/me/system_status"))

    # Compliance Summary (Snapshots)
    if "cluster_compliance_status" in args.sections:
        print("<<<rubrik_cluster_compliance_24_hours:sep(0)>>>")
        print(api.get_endpoint_data("internal/report/compliance_summary_24_hours"))

    # Cluster Nodes Data
    # Node Data
    if "node_status" in args.sections:
        for node in api.get_endpoint_data("internal/cluster/me/node").get("data", []):
            print(f"<<<<{node.get('id')}>>>>")
            print("<<<rubrik_node:sep(0)>>>")
            print(node)
            print("<<<<>>>>")

    # Node Disks
    if "node_disk_status" in args.sections:
        for disk in api.get_endpoint_data("internal/cluster/me/disk").get("data", []):
            print(f"<<<<{disk.get('nodeId', '').split(':::')[-1]}>>>>")
            print("<<<rubrik_node_disk:sep(0)>>>")
            print(disk)
            print("<<<<>>>>")

    # Node Hardware Health
    if "node_hardware_health" in args.sections:
        for node, health in api.get_endpoint_data("internal/cluster/me/hardware_health").items():
            print(f"<<<<{node}>>>>")
            print("<<<rubrik_node_hardware_health:sep(0)>>>")
            print(health)
            print("<<<<>>>>")

    return api.delete_token()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
