#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_mshpc_arguments(params, hostname, ipaddress):
    args = ['--url', params["url"]]
    args += ['--user', params["user"]]
    args += ['--secret', passwordstore_get_cmdline("%s", params["secret"])]
    if params.get('rows'):
        args += ['--rows', params["rows"]]
    if params.get('api'):
        args += ['--api', params["api"]]

    return args

special_agent_info['mshpc'] = agent_mshpc_arguments
